export const projects = [
  {
    title: "E-commerce Platform",
    subtitle: "Full-stack shopping solution",
    description:
      "A comprehensive e-commerce platform with payment integration, inventory management, and admin dashboard.",
    icon: "ShoppingCart",
    gradient: "from-blue-500 to-purple-600",
    tags: ["Next.js", "TypeScript", "Stripe", "PostgreSQL"],
    status: "Live",
    isPrivate: true,
  },
  {
    title: "Task Management App",
    subtitle: "Collaborative productivity tool",
    description:
      "A modern task management application with real-time collaboration, project tracking, and team analytics.",
    icon: "CheckSquare",
    gradient: "from-green-500 to-teal-600",
    tags: ["React", "Node.js", "Socket.io", "MongoDB"],
    status: "Live",
    isPrivate: false,
  },
  {
    title: "AI Chat Assistant",
    subtitle: "Intelligent conversation bot",
    description: "An advanced AI-powered chat assistant with natural language processing and context awareness.",
    icon: "MessageCircle",
    gradient: "from-purple-500 to-pink-600",
    tags: ["Python", "FastAPI", "OpenAI", "React"],
    status: "Beta",
    isPrivate: true,
  },
  {
    title: "Weather Dashboard",
    subtitle: "Real-time weather insights",
    description: "A beautiful weather dashboard with forecasts, interactive maps, and detailed meteorological data.",
    icon: "Cloud",
    gradient: "from-cyan-500 to-blue-600",
    tags: ["Vue.js", "D3.js", "Weather API", "Tailwind CSS"],
    status: "Live",
    isPrivate: false,
  },
  {
    title: "Portfolio Website",
    subtitle: "Personal brand showcase",
    description: "A responsive portfolio website showcasing projects, skills, and professional experience.",
    icon: "User",
    gradient: "from-orange-500 to-red-600",
    tags: ["Next.js", "Tailwind CSS", "Framer Motion"],
    isPrivate: true,
  },
  {
    title: "Analytics Dashboard",
    subtitle: "Data visualization platform",
    description: "A comprehensive analytics dashboard with real-time data visualization and reporting capabilities.",
    icon: "BarChart3",
    gradient: "from-indigo-500 to-purple-600",
    tags: ["React", "D3.js", "Node.js", "PostgreSQL"],
    status: "Development",
    isPrivate: false,
  },
]
